import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { FaLightbulb, FaPen, FaBook } from 'react-icons/fa';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen flex flex-col">
          <Header />
          <main className="flex-grow relative">
            {/* Background Icons */}
            <div className="absolute inset-0 opacity-20 pointer-events-none">
              <FaLightbulb className="absolute top-20 left-20 text-6xl text-primary" />
              <FaPen className="absolute bottom-20 right-20 text-6xl text-secondary" />
              <FaBook className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 text-6xl text-primary" />
            </div>
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
